app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
    
boutiques_list:
    path:     /boutiques
    defaults: { _controller: AppBundle:Boutiques:getBoutiques }  
    
boutiques_one:
    path:     /boutiques/{idboutique}
    defaults: { _controller: AppBundle:Boutiques:getBoutique }  
    
articles_list:
    path:     /articles
    defaults: { _controller: AppBundle:Articles:getArticles }  
    
articles_one:
    path:     /articles/{idarticle}
    defaults: { _controller: AppBundle:Articles:getArticle }  
    
places_list:
    path:     /places
    defaults: { _controller: AppBundle:Place:getPlaces }    
    
places_one:
    path:     /places/{place_id}
    defaults: { _controller: AppBundle:Place:getPlace }    
    
users_list:
    path:     /users
    defaults: { _controller: AppBundle:User:getUsers }    
    
users_ones:
    path:     /users/{id}
    defaults: { _controller: AppBundle:User:getUser }   