app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    
utilisateurs:
    type:     rest
    resource: AppBundle\Controller\UtilisateursController  
    
boutiques:
    type:     rest
    resource: AppBundle\Controller\BoutiquesController  
    
articles:
    type:     rest
    resource: AppBundle\Controller\ArticlesController  
    

