app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    

places_list:
    path:     /places
    defaults: { _controller: AppBundle:Place:getPlaces }    
    
places_one:
    path:     /places/{place_id}
    defaults: { _controller: AppBundle:Place:getPlace }    
    
users_list:
    path:     /users
    defaults: { _controller: AppBundle:User:getUsers }    
    
users_ones:
    path:     /users/{id}
    defaults: { _controller: AppBundle:User:getUser }   