app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    
utilisateurs_list:
    path:     /utilisateurs
    defaults: { _controller: AppBundle:Utilisateurs:getUtilisateurs }  
    
utilisateurs_one:
    path:     /utilisateurs/{idutilisateur}
    defaults: { _controller: AppBundle:Utilisateurs:getUtilisateur }   
    
boutiques_list:
    path:     /boutiques
    defaults: { _controller: AppBundle:Boutiques:getBoutiques }  
    
boutiques_one:
    path:     /boutiques/{idboutique}
    defaults: { _controller: AppBundle:Boutiques:getBoutique }  
    
articles:
    type:     rest
    resource: AppBundle\Controller\ArticlesController  
    

